/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
    "/telemetry/check-updates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check for updates
         * @description Check for available application updates. Returns platform-specific update information based on the target parameter.
         */
        get: operations["checkUpdates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/telemetry/crash-reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit crash report
         * @description Submit application crash reports for monitoring and debugging
         */
        post: operations["submitCrashReport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/telemetry/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Publish new version
         * @description Publish a new application version. Requires admin privileges.
         */
        post: operations["publishUpdate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
};
export type webhooks = Record<string, never>;
export type components = {
    schemas: {
        UpdateInfo: {
            /** @description Version number (without 'v' prefix) */
            version: string;
            /**
             * Format: uri
             * @description Download URL for the update package
             */
            url: string;
            /** @description Digital signature for the update package */
            signature: string;
            /** @description Release notes for the update */
            notes: string;
            /**
             * Format: date-time
             * @description Publication date in ISO 8601 format
             */
            pub_date: string;
        };
        CrashReport: {
            id: string;
            /** Format: date-time */
            timestamp: string;
            appVersion: string;
            platform: string;
            error: {
                message: string;
                stack?: string;
                /** @enum {string} */
                type: "javascript" | "tauri" | "network" | "unhandled" | "react";
                componentStack?: string;
                filename?: string;
                lineno?: number;
                colno?: number;
            };
            context: {
                sessionId: string;
                userId?: string;
                url: string;
                userAgent: string;
                lastActions: string[];
                logs: {
                    /** Format: date-time */
                    timestamp?: string;
                    /** @enum {string} */
                    level?: "DEBUG" | "INFO" | "WARN" | "ERROR";
                    file?: string;
                    message?: string;
                    data?: {
                        [key: string]: unknown;
                    };
                }[];
            };
            system: {
                os: string;
                arch: string;
                version: string;
                memory?: string;
            };
        };
        CrashReportRequest: {
            reports: components["schemas"]["CrashReport"][];
        };
        CrashReportResponse: {
            success: boolean;
            received: number;
            errors?: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
};
export type UpdateInfo = components['schemas']['UpdateInfo'];
export type CrashReport = components['schemas']['CrashReport'];
export type CrashReportRequest = components['schemas']['CrashReportRequest'];
export type CrashReportResponse = components['schemas']['CrashReportResponse'];
export type $defs = Record<string, never>;
export interface operations {
    checkUpdates: {
        parameters: {
            query: {
                /** @description Current application version */
                current_version: string;
                /** @description Target platform identifier */
                target: "darwin-aarch64" | "darwin-x86_64" | "windows-x86_64" | "linux-x86_64";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Update available - returns platform-specific update information */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateInfo"];
                };
            };
            /** @description No update available - client is on the latest version */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    submitCrashReport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrashReportRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrashReportResponse"];
                };
            };
        };
    };
    publishUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Version number of the new release */
                    version: string;
                    /** @description Release notes for the update */
                    notes: string;
                    /**
                     * Format: uri
                     * @description Download URL for Darwin/macOS package
                     */
                    darwin_url: string;
                    /** @description Digital signature for Darwin/macOS package */
                    darwin_sig: string;
                    /**
                     * Format: uri
                     * @description Download URL for Windows package
                     */
                    windows_url: string;
                    /** @description Digital signature for Windows package */
                    windows_sig: string;
                };
            };
        };
        responses: {
            /** @description Update published successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateInfo"];
                };
            };
        };
    };
}
